accordion changes for angular & react using stencil
lokeshdaiya-yash/PTG-UI-Library pull request #53
Opened 2024-02-08 14:05 UTC by chaitalimadde

2024-02-13 11:41 UTC, shivrjsharma commented on libs/ptg-ui-web-components/src/components/ptg-accordion/ptg-accordion.tsx
![image](https://github.com/lokeshdaiya-yash/PTG-UI-Library/assets/107458047/fae2b275-ab0a-4032-91f9-fcea5ef8416d)

Please format file before code commit and avoid unnecessary spaces and line breaks

2024-02-14 03:53 UTC, ZalawaHarsha requested changes

2024-02-14 03:53 UTC, ZalawaHarsha commented on libs/ptg-ui-web-components/src/components/ptg-accordion/ptg-accordion.tsx
> +          style={{ width: this.width }}>
why we need to give width here ? it should have 100% width. whoever consuming it can handle width from their container parent.

2024-02-19 04:54 UTC, ZalawaHarsha approved these changes

2024-02-19 04:55 UTC, merged